spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jpashop?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
        driverClassName: com.mysql.cj.jdbc.Driver
        username: admin
        password: mg&=nc+i[it;TH,NV06D$2xs{
    jpa:
        hibernate:
            ddl-auto: create
        # show-sql: true
        properties:
            dialect: org.hibernate.dialect.MySQL8InnoDBDialect
            hibernate:
                # "[default_batch_fetch_size]": 100
                "[format_sql]": true
                "[use_sql_comments]": true
    # data:
    #     web:
    #         pageable:
    #             default-page-size: 10
    #             max-page-size: 2000

logging.level:
    "[org.hibernate.SQL]": debug
    # "[org.hibernate.type]": trace